### ISSUE TITLE
Displaying on map

### ISSUE THREAD

**Issue by sergio-gimenez** [sergio-gimenez/HackUPC2019#2]
# Displaying the **DirectionsResult**

The `DirectionsResult` contains the result of the directions query, which you may either handle yourself, or pass to a `DirectionsRenderer` object, which can automatically handle displaying the result on a map.

**Comment by brunoibez** [comment]
[{'bounds': {'northeast': {'lat': -33.8135763, 'lng': 151.2088053}, 'southwest': {'lat': -33.89778769999999, 'lng': 151.0028728}}, 'copyrights': 'Map data ©2019 Google', 'legs': [{'arrival_time': {'text': '11:20am', 'time_zone': 'Australia/Sydney', 'value': 1570839631}, 'departure_time': {'text': '10:35am', 'time_zone': 'Australia/Sydney', 'value': 1570836943}, 'distance': {'text': '25.2 km', 'value': 25175}, 'duration': {'text': '45 mins', 'value': 2688}, 'end_address': 'Parramatta NSW 2150, Australia', 'end_location': {'lat': -33.8135763, 'lng': 151.0033711}, 'start_address': '483 George St, Sydney NSW 2000, Australia', 'start_location': {'lat': -33.873203, 'lng': 151.206968}, 'steps': [{'distance': {'text': '0.1 km', 'value': 124}, 'duration': {'text': '2 mins', 'value': 94}, 'end_location': {'lat': -33.8735668, 'lng': 151.2069088}, 'html_instructions': 'Walk to Town Hall Station', 'polyline': {'points': 'nzvmEqr{y[e@CBO@Kd@B@Ez@F?FH?A?A\\'}, 'start_location': {'lat': -33.873203, 'lng': 151.206968}, 'steps': [{'distance': {'text': '26 m', 'value': 26}, 'duration': {'text': '1 min', 'value': 18}, 'end_location': {'lat': -33.8730269, 'lng': 151.2070742}, 'html_instructions': 'Head <b>north</b> on <b>George St</b> toward <b>Park St</b>', 'polyline': {'points': 'nzvmEqr{y[e@CBO'}, 'start_location': {'lat': -33.873203, 'lng': 151.206968}, 'travel_mode': 'WALKING'}, {'distance': {'text': '10 m', 'value': 10}, 'duration': {'text': '1 min', 'value': 7}, 'end_location': {'lat': -33.8730383, 'lng': 151.2071319}, 'html_instructions': 'Turn <b>right</b> onto <b>Park St</b>', 'maneuver': 'turn-right', 'polyline': {'points': 'lyvmEes{y[@K'}, 'start_location': {'lat': -33.8730269, 'lng': 151.2070742}, 'travel_mode': 'WALKING'}, {'distance': {'text': '27 m', 'value': 27}, 'duration': {'text': '1 min', 'value': 20}, 'end_location': {'lat': -33.8732343, 'lng': 151.2071099}, 'html_instructions': 'Turn <b>right</b>', 'maneuver': 'turn-right', 'polyline': {'points': 'nyvmEqs{y[d@B'}, 'start_location': {'lat': -33.8730383, 'lng': 151.2071319}, 'travel_mode': 'WALKING'}, {'distance': {'text': '47 m', 'value': 47}, 'duration': {'text': '1 min', 'value': 34}, 'end_location': {'lat': -33.8735889, 'lng': 151.2070572}, 'html_instructions': 'Slight <b>left</b>', 'maneuver': 'turn-slight-left', 'polyline': {'points': 'tzvmEms{y[@Ez@F?FH?'}, 'start_location': {'lat': -33.8732343, 'lng': 151.2071099}, 'travel_mode': 'WALKING'}, {'distance': {'text': '14 m', 'value': 14}, 'duration': {'text': '1 min', 'value': 15}, 'end_location': {'lat': -33.8735668, 'lng': 151.2069088}, 'html_instructions': 'Take entrance <span class="location">Exit 2, George St</span>', 'polyline': {'points': 'z|vmEcs{y[A\\'}, 'start_location': {'lat': -33.873577, 'lng': 151.207062}, 'travel_mode': 'WALKING'}], 'travel_mode': 'WALKING'}, {'distance': {'text': '24.5 km', 'value': 24454}, 'duration': {'text': '36 mins', 'value': 2178}, 'end_location': {'lat': -33.8175326, 'lng': 151.0054527}, 'html_instructions': 'Train towards Penrith via Central', 'polyline': {'points': 'x|vmEer{y[AJp@FZBnAJ@?@?hDh@D?T?R?JCF?h@Mj@Uf@]b@_@b@e@LQLWLWLULUl@m@t@i@x@c@z@]d@MVI\\I~AQn@CF@hAN@?L@H?H?^Dt@LZDHBB?H@LBZF~BZl@JH@@@TDhARd@JZH`@JB@LBd@NdA^PFPHb@TTLhAp@p@f@`DvEt@d@Z^PR^j@zAvBz@nAf@n@r@zALd@n@dAT^`@l@V\\j@n@PP@@RRNNVRTRZV~B`Bv@j@JHZXJHJHt@p@p@j@t@n@r@n@^^PNJL\\`@X\\JNVZf@l@^l@Zd@BFFJXf@p@nAf@bAP`@Zr@b@hAXr@`@fAXv@Z~@Rp@Pp@Lb@FZJd@RbAFf@Jl@Jn@Ff@Jh@Hj@FZLj@Ld@Pr@Pt@FZ^bBTbAJ`@Lh@Lj@FXNl@BJH\\XlANr@FVPl@Rr@h@pB\\zAV`ALl@Lf@HZLl@R~@FR?BDNBL^|APr@@FZvAJl@NbA\\~C@DFl@F`A@J@VBnA?Z@l@?j@BnA?xA?P?~A?^Av@Cx@G~ACz@Al@?xA?JAXAr@CVCXCTEZKt@Qt@Q|@GRGTK^[`AQf@Sd@IRWh@KTc@x@k@`AYj@OXQ^Sd@KTITKZCFCJ[jAI^ERAFCHENg@pBCHEROd@]nAELa@tAYhAQx@ABCPQdAIh@Ip@CJAJCj@ANAJ?RCf@?JAxA?N@z@?d@B`@?JD~@FrABV@`@NtB@D?DXxC@NNvADf@Db@D|@Bh@A|@AdAGdAKtAMbAc@bCUfAk@bCWvAEXGr@Gp@ALIbAGjA?jABzA@PNbBd@dELrANlBH`B?D?pACjBKjBIfAWdCGt@KdASnBQdAMp@S~@_@vAEPOn@Qt@YpAIb@WrAGVGTc@jBCJc@hBGTI^A@Sx@ABOl@g@rBCLKj@q@|CW`AELa@bB_@rAg@xAOd@ITSl@St@Mf@K`@Ox@QbAMt@QlAKr@K`AGv@Ez@EdBA`AC|@?LA|@Ct@Ap@ATAnAA\\CnACdAAd@Ad@C\\?@Cf@?BEh@Gz@K~@Il@Gd@It@G\\CRId@I^I`@U|@Qx@EPUt@?@Mt@IZGTOn@ABSt@]nA_@rAMh@Oj@Ql@Sj@Mb@Oj@Oj@Ol@Sv@On@K`@On@Ov@Ib@ERADAHCHId@Mn@Kh@On@Mn@Qx@Ov@St@S|@St@YhAQr@Kb@CJIZA?GVGRWx@Sn@M`@KXITABCFKXSf@MXMX_@z@Sd@S`@cAxBc@`AOZEJ{@lBSb@m@tA]p@s@hAa@n@S\\MTOTEJaAbBA@MRGLYh@Ub@S\\k@bAi@v@m@z@eAvAKLcBzBkBdCa@j@u@nAOVCDQVWf@_@v@g@pAWt@Of@W~@Sv@Ml@I`@WnAc@|BWpAQdAWdBWrBGb@OxACXCVCRYnC?B_@rDObBMz@AJOt@Mj@IZUt@AFKXYt@_@z@m@nAEJGJWb@S\\SXUXa@d@]^GF_@`@STUVk@h@w@r@_Ax@q@j@a@^ILQNi@l@c@n@W^GJm@dAs@pAc@r@OVk@z@WZ[\\CD[\\[\\_@`@STIJYZKNKLi@n@e@n@UZ_@h@[d@Ub@OXUd@Yn@Sj@Yx@Ut@Wv@]~@Wn@e@|@k@fA[l@A@OZOVO^EL]v@_@dAUn@EL[x@i@zA[~@?@Od@CJIZMh@Ol@Id@S~@ETG\\CJKf@CJEPGPCNOt@EPKf@Ov@Or@S`AI\\?BWjAS`AUjASbAQv@In@CNG\\Gl@Gl@Gp@Cf@Ep@Ab@AZAn@A|@?l@@d@@d@@j@B`@?FBf@?@Dj@JdAJfALlAJxABp@Fz@B|@Dt@@R@R@TBt@B|@?r@?~@At@C|@Ad@Er@Ej@Eh@Gv@Gl@W|Ba@nDUfB[|AGb@EXEf@Gd@Gp@g@rESdDGtAGfCE|A?b@CnB?hB@jC@rABdCBlAHxAHhANxALfARtAHXHf@Jr@L~@JnA@T@TBt@@z@Av@CbBEx@EnACfAA~BB|CAfDAtA?~AGrG?DAlADnAAdBAhAKxBC\\Kz@It@Kx@GZGd@Qt@Ol@CLKb@Sl@Up@K\\A@Sl@Wn@O^Wf@OVOVU^QTOTW^W^UX]`@YZUT[XOPWRQNWPMJSLMJMHUNkEnC_Aj@yBrAyH|EiAp@eEhCIFsD~BaHhE[ROJu@d@A?[R}@h@_BbAeAp@SLiAt@g@\\EBqBvAIFgAv@{@t@[X[X[XONCB]\\[ZIH{A~AIJs@r@EFq@p@uAxAEB_A`AYXMHWPGFq@t@e@f@UVUNSPEDQLIHa@ZWRIHEFe@f@ST]\\WXa@`@MLILEFk@h@i@n@u@v@cAfAq@t@w@v@i@f@c@d@_@\\OHIF]\\cAdAyD|DaCjCyAbBe@l@o@~@y@lAoB`DoAhCkAxCiAvB]p@ELYh@ABc@n@KPEV_CjEa@v@g@`AOTwB~DaCpEMVMR?@qArB_CpEa@v@[l@y@~AABEFiAtB_@n@cBdDq@|@EHCDY`@ML_@b@ABc@b@e@b@o@d@q@b@SJ_@PIBMDgCfAq@Tq@RmA^aDz@[FUDSDK@O?m@FgBHyBDiDMeDYgB_@{A[mCUsBCS@aABaBFkB`@oAd@a@V]RQLgAr@oA`Aa@\\OLMJa@\\{@`A]d@QXIG'}, 'start_location': {'lat': -33.8735668, 'lng': 151.2069088}, 'transit_details': {'arrival_stop': {'location': {'lat': -33.8175326, 'lng': 151.0054527}, 'name': 'Parramatta'}, 'arrival_time': {'text': '11:13am', 'time_zone': 'Australia/Sydney', 'value': 1570839198}, 'departure_stop': {'location': {'lat': -33.8735668, 'lng': 151.2069088}, 'name': 'Town Hall Station'}, 'departure_time': {'text': '10:37am', 'time_zone': 'Australia/Sydney', 'value': 1570837020}, 'headsign': 'Penrith via Central', 'line': {'agencies': [{'name': 'Sydney Trains', 'phone': '011 61 131500', 'url': 'http://www.sydneytrains.info/'}], 'color': '#f2991b', 'name': 'North Shore, Northern & Western Line', 'short_name': 'T1', 'text_color': '#ffffff', 'vehicle': {'icon': '//maps.gstatic.com/mapfiles/transit/iw2/6/rail2.png', 'local_icon': '//maps.gstatic.com/mapfiles/transit/iw2/6/au-sydney-rail.png', 'name': 'Train', 'type': 'HEAVY_RAIL'}}, 'num_stops': 11}, 'travel_mode': 'TRANSIT'}, {'distance': {'text': '0.6 km', 'value': 597}, 'duration': {'text': '7 mins', 'value': 433}, 'end_location': {'lat': -33.8135763, 'lng': 151.0033711}, 'html_instructions': 'Walk to Parramatta NSW 2150, Australia', 'polyline': {'points': 'p~kmEagtx[?xATNi@dAGJ]r@Q\\IRQf@CFEVAJCPMB@NE@[@I?GCECGIMJ[NMFMDIBK@UBG@IAC?A?G?YDQBC@CBA@A@A@CBKJKFMDOBG@E?E?IAAHMCs@QaDu@w@QME'}, 'start_location': {'lat': -33.8175326, 'lng': 151.0054527}, 'steps': [{'distance': {'text': '41 m', 'value': 41}, 'duration': {'text': '1 min', 'value': 42}, 'end_location': {'lat': -33.817532, 'lng': 151.005005}, 'html_instructions': 'Take exit <span class="location">Liverpool-Parramatta T-way</span>', 'polyline': {'points': 'p~kmEagtx[?xA'}, 'start_location': {'lat': -33.8175326, 'lng': 151.0054527}, 'travel_mode': 'WALKING'}, {'distance': {'text': '0.2 km', 'value': 159}, 'duration': {'text': '2 mins', 'value': 110}, 'end_location': {'lat': -33.8168726, 'lng': 151.0033865}, 'html_instructions': 'Head <b>northwest</b> on <b>Liverpool-Parramatta Transitway</b> toward <b>Church St</b>', 'polyline': {'points': 'f_lmEwctx[i@dAGJ]r@Q\\IRQf@CFEVAJCPMB@N'}, 'start_location': {'lat': -33.8176357, 'lng': 151.0049151}, 'travel_mode': 'WALKING'}, {'distance': {'text': '42 m', 'value': 42}, 'duration': {'text': '1 min', 'value': 28}, 'end_location': {'lat': -33.816539, 'lng': 151.0034602}, 'html_instructions': 'Turn <b>right</b> onto <b>Church St</b>', 'maneuver': 'turn-right', 'polyline': {'points': 'lzkmEezsx[E@[@I?GCECGI'}, 'start_location': {'lat': -33.8168726, 'lng': 151.0033865}, 'travel_mode': 'WALKING'}, {'distance': {'text': '0.4 km', 'value': 355}, 'duration': {'text': '4 mins', 'value': 253}, 'end_location': {'lat': -33.8135763, 'lng': 151.0033711}, 'html_instructions': 'Turn <b>left</b> to stay on <b>Church St</b>', 'maneuver': 'turn-left', 'polyline': {'points': 'jxkmEszsx[MJ[NMFMDIBK@UBG@IAC?A?G?YDQBC@CBA@A@A@CBKJKFMDOBG@E?E?IAAHMCs@QaDu@w@QME'}, 'start_location': {'lat': -33.816539, 'lng': 151.0034602}, 'travel_mode': 'WALKING'}], 'travel_mode': 'WALKING'}], 'traffic_speed_entry': [], 'via_waypoint': []}], 'overview_polyline': {'points': 'nzvmEqr{y[e@CBO@Kd@B@Ez@F?FH?C\\AJp@FjBNB?nDh@h@?RCh@Mj@UjA}@p@w@v@{Al@m@t@i@tBaA|@W|B[v@AjAN`AFrG`AnATlDt@|Bt@|At@zBxA`DvEt@d@l@r@zBbDbB~Br@zALd@dAdBx@jArAvAxAnA~EpD~BpBzCnCnA|A~@hAz@rAvAjCx@dB~@|BpBrFz@bDr@~Dh@lDt@`D~BjKtBrIlB|Hx@pD`BfHz@vGRrCDdEBzGMpFEnEK~BIp@]jBm@fCkAbDsBzDoAjCe@nAo@jCkBfHsAfFa@dCStBGvA?pDHrC\\bG\\tD`@`F@fBIjCYxCy@jEcAzEMlA[nEBfDPtBd@dE\\`EHfBC|DUrD_@zD_@tD_@vBiAxEmA~FoBfImA~EyAxGg@pBgAlDaA~C{@fEw@xFMrBGfDI~DSvKGjAc@rE]lCs@dDm@bCo@vCwClK}@hD_AxD_A~E{@bEkA`FwAtFaB`FoAvCoCbGeBxDkAfCuAxBw@tAyAfCoBnDiDxEoE`GwAzB}@|AgAhCg@|AcAfEeBdJo@xEW|Be@tE}@vIi@hC}@lC{AbDuAtBgBnBmCjCqBdBk@l@{@|@{@nAmCvEsAnBoD~DgB|Bu@dAq@hAe@~@m@zAeBfF}@lBgAtBq@tAyAzDgBbF]nA{@|Ds@fD_B~HuA|Gg@tC[tDK`D@vDH|B\\zDXfDJlBLzCH|DAtBEbBY`EwAbMc@`CK`AOvAg@rESdDO|EE`CCxEB~EFrERbDp@vFR`AXrBRpD?rBI|CIvC@|GKpRArADnAAdBMbEOxAe@pDq@tCw@~Bk@|Ag@fAgAdBuAnBiBlBqAfAyMnIua@jWuK|GiD`CcClBw@r@mAjAkCpCaEfEeAdAg@b@_@XwA|AeA~@uAfAiAnAeBfBeBnBcFlFmAlAo@f@g@d@}FbG{EnFuAlBiDnFoAhCkAxCgBhD_@v@e@r@Qh@yEzIuG|LqAtBaDhG}AxCiBdDcBdDq@|@INg@n@kBnBaBhAs@\\WHyD|A_Cr@}DbAi@J[@uCPyBDiDMeDYgB_@{A[mCUgCAcDJkB`@oAd@_Aj@yA`AqB~A]X}A~Ao@~@IG?xATNi@dAe@~@q@`BGb@CPMB@NE@e@@MGGIMJi@VWHa@DQ?g@D[JSRq@RK?IAAHaAUyEgAME'}, 'summary': '', 'warnings': ['Walking directions are in beta. Use caution – This route may be missing sidewalks or pedestrian paths.'], 'waypoint_order': []}]
